name: Release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          release-type: node
  page:
    name: GitHub Page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ./public
      - run: cp ./packages/config/src/config.schema.json ./public
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
